### ISSUE TITLE
Local persistence of cloud-backed file targets

### ISSUE THREAD

**Issue by noamross** [ropensci/tarchetypes#101]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

Using AWS or other cloud-backed target storage is convenient for sharing the cache of built targets across users and having access to target version history.  However, there is a cost of some convenience of not having local targets on-disk to inspect, because targets deletes the file after uploading to cloud storage.

I suggest having an option for cloud backed files to persist on disk after the pipeline is run.  This way targets such as compiled reports and figures are available to inspect locally, but also are shared and versioned using the cloud cache.  Any running of targets would overwrite the file with the correct version from cloud storage.  targets need not examine this local file at all or consider it a cache (though a dual local/cloud "layered" cache might be an interesting option to facilitate online/offline options in the future).

For now, we have a reasonable workaround of using two targets:

```r
tar_target(cloud_file, some_big_process(outfile = "cloud_file.xxx"), format = "file", repository = "aws"),
tar_target(local_file, fs::file_copy(cloud_file, "local_file.xxx"), format = "file", repository = "local") 
## fs::file_copy returns the output filename, unlike base::file.copy
```

cc @emmamendelsohn @n8layman

**Comment by wlandau** [comment]
Because how complicated the cloud storage internals could get, I would prefer to handle this in `tarchetypes`. I would be open to a target factory like your workaround, but with `local_file` as the upstream target and `cloud_file` as the downstream target (to avoid an extra download). Would you be willing to send a PR?

**Comment by noamross** [comment]
It'll take a bit, but I'll put it on the to-do!

**Comment by noamross** [comment]
I realize an issue with `local_file` being upstream is that one does not get the benefit of cloud-based versioning to retrieve versions of the target rather than re-computing. In our workflows we tend to favor saving compute time over up/download.

**Comment by wlandau** [comment]
Right, that's a good point. In that case, I am fine with the original order you proposed if the function name and docs make the intent clear.

Thanks for your willingness to help.

**Comment by wlandau** [comment]
I am looking back at this issue again. Given how you use `targets`, I can see how it would be helpful to have a target factory to upload a file to the cloud and then download it again. But for everyone else, this seems only a little better than `tar_read()` on the cloud target, and it I do not think a function this specific would be easily discoverable or understood. So I would prefer not to canonize it in `tarchetypes`. But if you and your team want to write a custom target factory for yourselves, I wrote general guidance at <https://wlandau.github.io/targetopia/contributing.html>. I would be happy to jump in and troubleshoot roadblocks as they arise.
