### ISSUE TITLE
combine tar_cue_age with a conditional statement

### ISSUE THREAD

**Issue by melissakey** [ropensci/tarchetypes#108]
Is it possible to create cue based on both a conditional expression (e.g. like `tar_cue_skip`) and age (`tar_cue_age`)?

Brief context:
I can only access an internal server for new data when I'm physically at my work, but I also work from home frequently.  When I'm at work, I only want to download new data about every week or so - otherwise I tend to rerun a lot of the pipeline unnecessarily.   I'm looking for a way to check the time since the last download *and* another condition (access to the internal server)

I tried using 
```
tar_age(target_name,
  fun(x),
  age = as.difftime(5, units = 'days'),
  cue = tar_cue_skip(!file.exists(remote_server_address)),
  error = 'continue',
)
```
but for some reason I have only half understand, this produced a result where the target always ran, regardless of the age and server.  

The half I understand: apparently `tar_cue_skip` works by changing the mode to 'never' when the skip condition is met.  As is fully documented in `tar_age`, the mode argument of `cue` is totally ignored by `tar_age`, so this is as-intended (if non-ideal for my purposes).

I don't understand is why setting `cue = tar_cue_skip` causes `age=as.difftime(5, units = 'days')` to be ignored entirely (or so it appears, but maybe I'm missing something?)  - but maybe I'm missing something?

For now, I'm setting error to 'continue' and removing the cue statement.  I'm hoping that will let things work (with some ignored errors when not connected to the server), and I think that will work for now - but it feels somewhat ugly & dangerous.

**Comment by melissakey** [comment]
I feel like half the time I scratch my head for half a day, post something, then figure out a solution 5 minutes later.  The following seems to work:

```
tar_target(target_name,
  fun(x),
  cue = tar_cue_skip(!file.exists(remote_server_address) & difftime(Sys.time(), tar_timestamp(target_name), units = 'days') < 5),
  error = 'continue'
)
```

Unless there is some reason not to do it this way, that does the trick.

**Comment by wlandau** [comment]
Glad you figured it out.

**Comment by wlandau** [comment]
The upstream target needs to check if the file names changes since last run, which requires rerunning the upstream target. `tar_files()` and `tar_files_input()` try to make the most common simple cases easy to write, and they may not fit the less common edge cases which may be more complicated. You may want to write your own custom `tar_target()` calls that borrow from the idea of `tar_files()`.
