### ISSUE TITLE
tar_cross()

### ISSUE THREAD

**Issue by potash** [ropensci/tarchetypes#132]
## Prework

* [x] I understand and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and  [contributing guidelines](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/tarchetypes/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Maybe I missed it in the documentation but there are a few extensions to static branching that I think would improve the generality and usefulness. The first I have written is called `tar_cross()`. I use this when I have one `tar_map()` and I wish to augment it with more variables into a bigger `tar_map()` and pass the context/environment of the smaller `tar_map()` into the bigger one.

Here is an example. The `old_names` argument is obviously very poorly implemented. It should be expanded to take the same values as `names` in `tar_map()` but I don't know enough about tidy evaluation to make that happen.

Also note that `tar_cross(new_values, old_targets, old_values, old_names)` could be streamlined into `tar_cross(new_values, old_targets)` if the list returned by `tar_map()` included its values and names arguments in some hidden attribute.

```r
targets::tar_dir({ # tar_dir() runs code from a temporary directory.
  targets::tar_script({
    library(targets)
    library(tarchetypes)
    library(dplyr)

    tar_cross = function(new_values, old_targets, old_values, old_names) {
      # create an empty dataframe with colnames equal to old target names
      vec = names(old_targets)
      old_vars <- bind_rows(setNames(rep("", length(vec)), vec))[0, ]
      
      new_values %>%
        bind_rows(old_vars) %>%
        mutate(across(all_of(vec), ~ rlang::syms(paste0(cur_column(), "_", get(old_names)))))
    }
    
    x_values = tibble(a = c("j", "k"))
    
    x_targets = tar_map(
      x_values,
      tar_target(x, a)
    )
    
    xy_values = x_values %>%
      tidyr::expand_grid(b = c("l", "m")) %>%
      tar_cross(x_targets, x_values, "a")
    
    xy_targets = tar_map(
      xy_values,
      names=c(a,b),
      tar_target(xy, paste0(x, b))
    )
    
    list(
      x_targets, 
      xy_targets
      )
  })
  targets::tar_manifest()
})
```

**Comment by wlandau** [comment]
It's a good thought, but nested `tar_map()`s already handle cases like this one.

```r
# _targets.R file:
library(targets)
library(tarchetypes)
tar_map(
  list(a = c("j", "k")),
  tar_target(x, a),
  tar_map(list(b = c("l", "m")), tar_target(xy, paste0(x, b)))
)
```

**Comment by potash** [comment]
Great, thanks!
