### ISSUE TITLE
Bug: `tar_quarto_rep()` throws an error if used together with `future::plan()` from _targets.R template

### ISSUE THREAD

**Issue by MirzaCengic** [ropensci/tarchetypes#136]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Issue

I've had issues with running `tar_quarto_rep()`, and it would throw me a following error message: 

> Caused by error in `set.seed()`: ! supplied seed is not a valid integer

or if I would add `tar_option_set(error = "null")`:

> report_0a9275f7                        1m22m36mℹ39m In index 1.1mCaused by error in set.seed22m33m39m supplied seed is not a valid integer

This error is reproducible only if line `future::plan(future.callr::callr)` from default _targets.R template is used. I didn't go any further trying to debug the issue (finding that removing this line fixes the issue took me way to long). This works with the example from function documentation. I'm using `targets_0.14.1` and `tarchetypes_0.7.3` 

```
# This example works fine.
targets::tar_dir({ # tar_dir() runs code from a temporary directory.
    # Parameterized Quarto:
    lines <- c(
      "---",
      "title: 'report.qmd file'",
      "output_format: html_document",
      "params:",
      "  par: \"default value\"",
      "---",
      "Assume these lines are in a file called report.qmd.",
      "```{r}",
      "print(params$par)",
      "```"
    )
    writeLines(lines, "report.qmd") # In tar_dir(), not the user's file space.
    # The following pipeline will run the report for each row of params.
    targets::tar_script({
      library(tarchetypes)      
      list(
        tar_quarto_rep(
          report,
          path = "report.qmd",
          execute_params = tibble::tibble(par = c(1, 2))
        )
      )
    }, ask = FALSE)
    # Then, run the targets pipeline as usual.
    targets::tar_make()
  })
```

```
# This example throws an error 
targets::tar_dir({ # tar_dir() runs code from a temporary directory.
    # Parameterized Quarto:
    lines <- c(
      "---",
      "title: 'report.qmd file'",
      "output_format: html_document",
      "params:",
      "  par: \"default value\"",
      "---",
      "Assume these lines are in a file called report.qmd.",
      "```{r}",
      "print(params$par)",
      "```"
    )
    writeLines(lines, "report.qmd") # In tar_dir(), not the user's file space.
    # The following pipeline will run the report for each row of params.
    targets::tar_script({
      library(tarchetypes)
      
 
      future::plan(future.callr::callr)    # line causing the bug  
      
      list(
        tar_quarto_rep(
          report,
          path = "report.qmd",
          execute_params = tibble::tibble(par = c(3, 4))
        )
      )
    }, ask = FALSE)
    # Then, run the targets pipeline as usual.
    targets::tar_make()
  })
```

P.S. apologies for not opening an issue properly; I've spent 15 minutes trying to figure out how to do it for a bug report, but couldn't get past "new feature" label.

**Comment by wlandau** [comment]
Thanks for the reprexes. I reproduced the error with `tarchetypes` 0.7.3 and confirmed it is fixed in version 0.7.4 (current CRAN). Please try upgrading your copy of the package.
