### ISSUE TITLE
Expose `tar_render()`, `tar_quarto()` and similar functions to the `deps` argument of `tar_target_raw()`

### ISSUE THREAD

**Issue by NFA** [ropensci/tarchetypes#140]
## Prework

* [✔️] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [✔️] I understand and agree to [contributing guide](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [✔️] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal
Functions like `tar_render()` and `tar_quarto()` call `targets::tar_target_raw()` but are not exposed to the `deps` argument of `tar_target_raw()`. I propose that they should be exposed to this argument, so that a user can specify adjacent dependencies not automatically deduced by the targets pipeline.

## Context
I do academic research. I use `targets` to create a reproducible workflow from raw data to finalized manuscript ready for journal submission. It is very common that journals request the individual figure files during the manuscript submission process. Adding the figures using `tar_read(plot_obj)` or by markdown (png/pdf) leads to different scaling of the figures,  depending on the template layout of the journal (one-column vs two-column, difference in margin sizes, etc). Therefore I prefer saving the figures to pdf/png where I can precisely control the proportions of the figure specifying width and length manually (and dpi for png). Then I am certain that the individual figure files look the same as the embedded figures in the manuscript. However I cannot make my markdown or quarto documents depend on saved figure files as the `deps` is not exposed.

# Reproducible example
```
library(targets)

tar_script({
   library(tarchetypes)
   tar_option_set(packages = c("ggplot2"))
   list(
      tar_target(iris_plot_obj, ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + geom_point()),
      tar_target(iris_plot_png, ggsave("iris.png", iris_plot)),
      tar_render(report, "report.rmd"),
      tar_target_raw("iris_deps", 42, deps = c("iris_plot_png"))
      #tar_render(report, "report.rmd", deps = c("iris_plot_png")) <- would function with proposal
   )
}, ask = FALSE)

lines <- c(
   "---",
   "title: Document",
   "---",
   "![Iris](iris.png)"
)
           
writeLines(lines, "report.rmd")

tar_make()
```
Target `report ` does not depend on the `iris_plot_png`. Adding `deps` argument would result in error as it is not exposed. `tar_target_raw` already has the functionality of specify deps, as target `iris_deps` here is manually made dependant upon it.

![vis](https://user-images.githubusercontent.com/988662/227146983-6167a4f3-6add-4ee5-8967-5acdbe1e8434.png)

**Comment by gorkang** [comment]
An important issue with my approach is that you will get errors when including models and gtsummary tables in `params`. Not sure why, but my guess is that those are not welcomed by yaml.

So, my vote would go towards exposing `deps`.

**Comment by wlandau** [comment]
What about `format = "file"` for the PNG file and then `tar_load()` in the report? `_targets.R`:

```r
library(targets)
library(tarchetypes)
tar_option_set(packages = "ggplot2")
list(
  tar_target(
    iris_plot,
    ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) +
      geom_point()
  ),
  tar_target(
    iris_plot_png, {
      ggsave("iris.png", iris_plot)
      "iris.png"
    },
    format = "file" # https://books.ropensci.org/targets/data.html#external-files
  ),
  tar_render(report, "report.Rmd")
)
```

`report.Rmd`:

    ---
    title: document
    ---
    
    ```{r}
    knitr::include_graphics(targets::tar_read(iris_plot_png))
    ```

**Comment by gorkang** [comment]
What would be the way to do this when we have lots of targets we need to track?

An issue with using `tar_read()` or `tar_load()` is that you need to input the targets one by one, which becomes unreasonable with a big number of targets.

For example:

`_targets.R`:  

```
library(targets)
library(tarchetypes)
tar_option_set(packages = "ggplot2")

list(
  tar_target(DF1, ggplot2::mpg),
  
  tarchetypes::tar_map(
    values = tibble::tibble(ID = 1:5),
    
    tar_target(
      OBJECT, DF1 |> dplyr::mutate(A= ID)
    )
  ),

tar_render(report, "report.Rmd")
)

```



`report.Rmd`:  

```

---
title: document
---

```{r}
# Works, but forces you to manually write down ALL the objects
targets::tar_load(OBJECT_1)
targets::tar_load(OBJECT_2)
targets::tar_load(OBJECT_3)
targets::tar_load(OBJECT_4)
targets::tar_load(OBJECT_5)

# Works but targets won't detect the relationship
# ALL_OBJECTS = targets::tar_objects(names = starts_with("OBJECT"))
# targets::tar_load(all_of(ALL_OBJECTS))

# THIS DOES NOT WORK
# targets::tar_read(ALL_OBJECTS)
```

```

**Comment by wlandau** [comment]
> An issue with using tar_read() or tar_load() is that you need to input the targets one by one, which becomes unreasonable with a big number of targets.

I do not think this scenario fits the underlying philosophy of literate programming. The rendered document should be human-readable, and each figure should have a section of prose to interpret it. A single call to `tar_read(your_plot_object)` or `include_graphics(tar_read(your_plot_file))` is very little text compared with the paragraph that explains the output.

If you are still worried about a large number of `tar_read()` or `tar_load()` calls, you could add a target in the pipeline that depends on everything you want the report to depend on, then call `tar_load(downstream_target)` in the report once.

The `tar_target_raw()` function and the `deps` argument are intended for developers and not users.

**Comment by NFA** [comment]
Hi, just want to leave a final comment here. Firstly, I want to express my thanks for the `targets` package and all the work you do regarding it and the other packages in the targets ecosystem. This week I will look into what it will take to include my stan models for my current paper into the pipeline using `stantargets`. I think `targets` may the the most useful package around in the R ecosystem for reproducible workflows today, so big kudos. For the time being, I don't see myself using anything else. Few closing points:

1. I think inserting an R code chunk with knitr loading the image is the less elegant solution (my subjective opinion). It brings both cognitive and computational overload compared to just using the markdown syntax for image files. 
2.  I would say that `tar_target_raw()` being exported in the `NAMESPACE` is a signal that the function is intended for end user consumption.
