### ISSUE TITLE
Let `tar_map()` substitute more fields, e.g., `priority`

### ISSUE THREAD

**Issue by psychelzh** [ropensci/tarchetypes#168]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

`targets::tar_map()` will set many targets at once, but sometimes I want set priority for them, especially when they take different time to finish. When they are executed in parallel, I guess it would be more efficient if we could let the most time-consuming tasks (if we could predict) start first. For example, this pipeline:

```r
# _targets.R
library(targets)
tarchetypes::tar_map(
  data.frame(name = letters[1:5], prior = 1:5 / 5),
  names = name,
  tar_target(
    test,
    sleep(prior * 100)
  )
)
```

It would benefit a lot if we could set:

```r
# _targets.R
library(targets)
tarchetypes::tar_map(
  data.frame(name = letters[1:5], prior = 1:5 / 5),
  names = name,
  tar_target(
    test,
    sleep(prior * 100),
    priority = prior
  )
)
```

Unfortunately, it does not support this yet. Although we could fulfill it with `tarchetypes::tar_eval()`, it is much harder and does not support multiple targets.

``` r
targets::tar_dir({
  targets::tar_script({
    library(targets)
    tarchetypes::tar_map(
      data.frame(name = letters[1:5], prior = 1:5 / 5),
      names = name,
      tar_target(
        test,
        sleep(prior * 100),
        priority = prior
      )
    )
  })
  targets::tar_make()
})
#> Error:
#> ! Error running targets::tar_make()
#> Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
#> Debugging guide: https://books.ropensci.org/targets/debugging.html
#> How to ask for help: https://books.ropensci.org/targets/help.html
#> Last error message:
#>     object 'prior' not found
#> Last error traceback:
#>     base::tryCatch(base::withCallingHandlers({ NULL base::saveRDS(base::do.c...
#>     tryCatchList(expr, classes, parentenv, handlers)
#>     tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), na...
#>     doTryCatch(return(expr), name, parentenv, handler)
#>     tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
#>     tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>     doTryCatch(return(expr), name, parentenv, handler)
#>     base::withCallingHandlers({ NULL base::saveRDS(base::do.call(base::do.ca...
#>     base::saveRDS(base::do.call(base::do.call, base::c(base::readRDS("C:\\Us...
#>     base::do.call(base::do.call, base::c(base::readRDS("C:\\Users\\lenovo\\A...
#>     (function (what, args, quote = FALSE, envir = parent.frame()) { if (!is....
#>     (function (targets_function, targets_arguments, options, envir = NULL, s...
#>     tryCatch(out <- withCallingHandlers(targets::tar_callr_inner_try(targets...
#>     tryCatchList(expr, classes, parentenv, handlers)
#>     tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>     doTryCatch(return(expr), name, parentenv, handler)
#>     withCallingHandlers(targets::tar_callr_inner_try(targets_function = targ...
#>     targets::tar_callr_inner_try(targets_function = targets_function, target...
#>     eval(parse(file = script, keep.source = TRUE), envir = envir)
#>     eval(parse(file = script, keep.source = TRUE), envir = envir)
#>     tarchetypes::tar_map(data.frame(name = letters[1:5], prior = 1:5/5), nam...
#>     unlist(list(...), recursive = TRUE) %|||% list()
#>     unlist(list(...), recursive = TRUE)
#>     tar_target(test, sleep(prior * 100), priority = prior)
#>     tar_target_raw(name = name, command = command, pattern = pattern, packag...
#>     tar_assert_dbl(priority)
```

<sup>Created on 2024-02-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by wlandau** [comment]
I see what you mean, but I hesitate because `tar_map(names = everything())` is so common that the change might not be back-compatible and those targets would be prone being renamed when the priorities change.

There is an equally strong case to implement mapping for all other arguments of `tar_target()`, including `cue`. A fully-realized version of this feature would do that, but for the same reasons, arguments like `cue` and `resources` would not be feasible to map. So if I were to do this just for priority, it would feel like an incomplete feature without clear encapsulation on the behaviors.

For you, you could loop over the target list and edit the `$settings$priority` field of each one. I don't generally recommend this because the internal objects of `targets` have no back-compatibility guarantees, but I know you know what you're doing, and I have hardly needed to refactor the object-oriented structure of a target object since I created `targets` in 2020.

**Comment by psychelzh** [comment]
Thanks! For now, it works perfectly by setting `$settings$priority` manually.
