### ISSUE TITLE
Export `tar_format_alias()`

### ISSUE THREAD

**Issue by anthonynorth** [ropensci/tarchetypes#171]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Can we export `tarchetypes::tar_format_alias()`?

I'd like to be able to create wrapper `tar_custom_format()` tarchetypes with minimal effort. The most straight-forward approach that I'm aware of is using the internal `tarchetypes::tar_format_alias()` function.

Roughly equivalent approaches:
- Copy-paste `targets::tar_target()` and modify `format`
- Construct a function with `rlang::new_function`
  ```r
  tar_parquet_table <- {
    fmls <- rlang::fn_fmls(targets::tar_target)
    fmls$format <- tar_format_parquet_table() # a custom format
    rlang::new_function(fmls, rlang::fn_body(targets::tar_target))
  }
  ```

Example usecase: Store data frames/arrow tables as parquet, read as arrow table.

```r
tar_format_parquet_table <- function() {
  tar_format(
    read = function(path) arrow::read_parquet(path, as_data_frame = FALSE),
    write = function(object, path) arrow::write_parquet(object, path)
  )
}

tar_parquet_table <- tarchetypes:::tar_format_alias(tar_format_parquet_table())
```

**Comment by wlandau** [comment]
The mechanism behind `tar_format_alias()` is a bit strange, and I would prefer to keep it internal. In your case, you could create a target factory using `tar_target_raw()`: https://wlandau.github.io/targetopia/contributing.html. [`geotargets`](https://github.com/njtierney/geotargets) takes this approach with  [`tar_terra_rast()](https://github.com/njtierney/geotargets/blob/master/R/tar-terra-rast.R).

**Comment by anthonynorth** [comment]
Thanks Will.

I was hoping to avoid copy-paste boilerplate when making a `tar_x` alias. This is particularly applicable in cases where I'm defining a custom format within a project. 

Would you consider exposing a new `tar_target()` factory function instead, which is really just a simple wrapper over `tar_target()` itself? Something like:

```r
tar_target_format_factory <- function(format) {
  function(
    name,
    command,
    pattern = NULL,
    tidy_eval = targets::tar_option_get("tidy_eval"),
    packages = targets::tar_option_get("packages"),
    library = targets::tar_option_get("library"),
    repository = targets::tar_option_get("repository"),
    iteration = targets::tar_option_get("iteration"),
    error = targets::tar_option_get("error"),
    memory = targets::tar_option_get("memory"),
    garbage_collection = targets::tar_option_get("garbage_collection"),
    deployment = targets::tar_option_get("deployment"),
    priority = targets::tar_option_get("priority"),
    resources = targets::tar_option_get("resources"),
    storage = targets::tar_option_get("storage"),
    retrieval = targets::tar_option_get("retrieval"),
    cue = targets::tar_option_get("cue"),
    description = targets::tar_option_get("description")
  ) {
    # omitted
  }
}
```
