### ISSUE TITLE
Scan included files for changes when rendering qmd/Rmd

### ISSUE THREAD

**Issue by turbanisch** [ropensci/tarchetypes#174]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

I am using `tar_quarto()` to render a report that embeds other qmd/md files via `{{< include my_other_file.qmd >}}`. Changes in those embedded files currently do not trigger a re-run of the target. Perhaps that would be something worth implementing?

**Comment by wlandau** [comment]
`tarchetypes` relies on `quarto::quarto_inspect()` to tell us which files are important, so unfortunately this is not under my control. A comment or thumbs-up at https://github.com/quarto-dev/quarto-cli/issues/8397 might help.

**Comment by turbanisch** [comment]
Good to know, thanks a lot for the fast reply! 🙏
