### ISSUE TITLE
How about adding `names_sep` argument to `tar_map()`

### ISSUE THREAD

**Issue by psychelzh** [ropensci/tarchetypes#177]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Currently, `tar_map()` will always use `_` as names separator, which is unfavorable when there is already `_` in names, showing the ideal situation of setting custom separator.

**Comment by wlandau** [comment]
Good idea, implemented as a new "delimiter" argument in dc552e9561721ea7d4f19154fd5aea5cce6bf54f.
