### ISSUE TITLE
Raw hook functions

### ISSUE THREAD

**Issue by multimeric** [ropensci/tarchetypes#185]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Currently the `hook` argument for the hook functions are quoted:

https://github.com/ropensci/tarchetypes/blob/8eb30c1b036edc03fc30a499f029064b1bc3033e/R/tar_hook_before.R#L56

This is convenient for common usability, but it means that we can't really do anything dynamic with that argument. For example, we can't construct a dynamic expression using our own `substitute()`. 

In addition, I would love for `tarchetypes:::walk_targets` to be exported, because it's so useful for building utilities on top of targets.

**Comment by wlandau** [comment]
Nice idea, added in https://github.com/ropensci/tarchetypes/commit/812b737a63929fc06f0526d8cc7291db86b84ac9
