### ISSUE TITLE
New DSL: tar_assign()

### ISSUE THREAD

**Issue by wlandau** [ropensci/tarchetypes#186]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Proposed by @hadley in https://github.com/ropensci/targets/issues/1309. The syntax is [arguably more pleasing](https://github.com/ropensci/targets/issues/1309#issuecomment-2260501760) than in `tar_plan()` because statements use `<-` and are not comma-separated. Sketch based on https://github.com/ropensci/targets/issues/1309#issue-2436390741:

```r
tar_assign({
  file <- tar_target("data.csv", format = "file")

  data <- read_csv(file, col_types = cols()) |> 
    filter(!is.na(Ozone)) |> 
    tar_target()
  
  model <- lm(Ozone ~ Temp, data) |> 
    coefficients() |> 
    tar_target()
  
  plot <- {
      ggplot(data) +
        geom_point(aes(x = Temp, y = Ozone)) +
        geom_abline(intercept = model[1], slope = model[2]) +
        theme_gray(24) 
    } |> 
      tar_target()

  simulations <- sample.int(10) |>
    tar_rep(batches = 2)
})
```

This will define a pipeline equivalent to:

```r
list(
  tar_target(file, "data.csv", format = "file"),
  tar_target(
    data,
    read_csv(file, col_types = cols()) |> 
      filter(!is.na(Ozone))
  ),
  tar_target(
    model,
    lm(Ozone ~ Temp, data) |> 
      coefficients()
  ),
  tar_target(
    plot,
    ggplot(data) +
      geom_point(aes(x = Temp, y = Ozone)) +
      geom_abline(intercept = model[1], slope = model[2]) +
      theme_gray(24)
  ),
  tar_rep(simulations, sample.int(10), batches = 2)
)
```

**Comment by multimeric** [comment]
Wonderful feature. Some interesting feedback from Mastodon:
* It's not clear if this syntax supports target factories inside of `tar_assign`. I think this is a fair use case because `tar_assign` is generally going to be the top level target factory, and then a user might want to use something like `tar_map` (static branching) inside `tar_assign`. However `tar_assign` always evaluates `x <- f()` as `f(x)`, which doesn't seem compatible with target factories that create multiple targets and don't require a name per se.
* Invalid syntax isn't easily captured. If you forget the `tar_target()` call (and I expect this will happen a lot), you get a confusing error:
```R
targets::tar_script({
  tarchetypes::tar_assign({
    x <- targets::tar_target(1)
    y <- 3
    z <- tar_target(x + y)
  })
})
targets::tar_make()
```
```
## Error:
## ! Error running targets::tar_make()
## Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
## Debugging guide: https://books.ropensci.org/targets/debugging.html
## How to ask for help: https://books.ropensci.org/targets/help.html
## Last error message:
##     object 'y' not found
## Last error traceback:
##     .handleSimpleError(function (condition)  {     state$error <- build_mess...
##     h(simpleError(msg, call))
```

**Comment by wlandau** [comment]
> It's not clear if this syntax supports target factories inside of tar_assign. I think this is a fair use case because tar_assign is generally going to be the top level target factory, and then a user might want to use something like tar_map (static branching) inside tar_assign. However tar_assign always evaluates x <- f() as f(x), which doesn't seem compatible with target factories that create multiple targets and don't require a name per se.

`tar_map()` is the only target factory that comes to mind which does not begin with a `name` argument. In any case, almost all target factories do, so I think it is a fair assumption. It's an indispensable one, at any rate.

> Invalid syntax isn't easily captured. If you forget the tar_target() call (and I expect this will happen a lot), you get a confusing error:

Added an informative error for that case in c95761e34013172dcc032f5421712d22db232ecf.

**Comment by chitrams** [comment]
Hello! First of all, thank you for developing and maintaining this package. This is fabulous–I'm a big fan and regular user :)

Apologies in advance if this is a silly question, as I'm relatively new to package development. Is `tar_assign()` already implemented as a new feature in the latest release? Or is this still being tested? When I installed the latest version from GitHub using `remotes`, `tar_assign()` didn't automatically pop up as an option from the list of functions (in the RStudio IDE).

I hope I don't come across as impatient. I was just wondering how far along the pipeline this is, as I'm excited to use the new syntax. Thank you again!

**Comment by multimeric** [comment]
It's not currently released on CRAN, but you can get it from the dev version using `remotes::install_github("ropensci/tarchetypes")`.

**Comment by chitrams** [comment]
Hi @multimeric, thank you for your quick response :)

I did install the dev version using `remotes::install_github("ropensci/tarchetypes")` but I came across the following error:

``` r
tar_assign({
    file <- tar_target("./data/raw_data_2024-08-24.csv", format = "file")
    data <- tar_target(read_csv(file))
})
#> Error in tar_assign({: could not find function "tar_assign"
```

<sup>Created on 2024-09-11 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by multimeric** [comment]
You might have to restart R to ensure it's loading the new version.

**Comment by chitrams** [comment]
Ah, of course! Sorry about that--that did fix it. Thank you so much for your help! :)
