### ISSUE TITLE
tar_assign should allow use of `=` as well as `<-`

### ISSUE THREAD

**Issue by rmflight** [ropensci/tarchetypes#188]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

In R, the use of `=` is **almost** as valid as `<-`, in my 5 years of programming R since switching to `=` over `<-`, I have encountered 0 issues related to its use (and saved some R6 related bugs to accidentally using `<-` in a list assignment).

Given the new DSL in `tar_assign` (which is really nifty, love the idea), I think it should support the use of `=` as the assignment operator.

The one wrinkle I've discovered in testing this, is that if one wants to use the `=` in every case, the code must be wrapped in `{ }`, whether using a single or multiline.

**Comment by wlandau** [comment]
Thanks for the PR
