### ISSUE TITLE
Consider an options object?

### ISSUE THREAD

**Issue by hadley** [ropensci/tarchetypes#192]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

i.e. https://design.tidyverse.org/argument-clutter.html

So instead of 

```R
tar_render(
  name,
  path,
  output_file = NULL,
  working_directory = NULL,
  tidy_eval = targets::tar_option_get("tidy_eval"),
  packages = targets::tar_option_get("packages"),
  library = targets::tar_option_get("library"),
  error = targets::tar_option_get("error"),
  memory = targets::tar_option_get("memory"),
  garbage_collection = targets::tar_option_get("garbage_collection"),
  deployment = "main",
  priority = targets::tar_option_get("priority"),
  resources = targets::tar_option_get("resources"),
  retrieval = targets::tar_option_get("retrieval"),
  cue = targets::tar_option_get("cue"),
  description = targets::tar_option_get("description"),
  quiet = TRUE,
  ...
)
```

You'd have

```
tar_render(
  name,
  path,
  output_file = NULL,
  working_directory = NULL,
  options = NULL,
  quiet = TRUE,
  ...
)
```

I'm pretty sure you can do this in a backward compatible way because you already have `...`, and would just need to extract out possible options arguments.

**Comment by wlandau** [comment]
This sounds appealing for both `tarchetypes` and `targets`. Argument clutter is a particular issue for target factories, especially in `stantargets`.

**Comment by wlandau** [comment]
On reflection, I do find it convenient to have arguments like `retrieval ` and `memory` at the top level because of how generally applicable they are. I remember my initial confusion as a new R programming trying to dig through nested option lists.

The existing `resources` argument of `tar_target()` actually reduces most of the argument clutter that could have been. The `resources` argument serves as an options object for advanced situations: cloud storage configuration, optimizations for data compression in `qs::qsave()`, the polling interval for data file updates on network file systems, etc. `targets` draws the line at common arguments vs esoteric ones.

I would also want to make the interface consistent among `tar_target()`, `tar_render()`, and all other target factories, which is a heavy and painful refactor at this point.

**Comment by hadley** [comment]
If it's just a matter of development time, we can help there 😄

**Comment by wlandau** [comment]
Thanks for offering help!

My reluctance to change the interface comes from all the above, not just the work it would take.

Also, these arguments can change a lot in a single pipeline. For example, this sort pattern is common:

```r
list(
  tar_target(
    name = data,
    command = get_data(),
    format = "qs"
  ),
  tar_rep(
    name = simulations,
    command = run_simulations(data),
    memory = "transient",
    garbage_collection = TRUE,
    retrieval = "worker"
  ),
  tar_target(
    name = app,
    command = create_wasm_bundle(simulations),
    deployment  = "local",
    format = "file"
  )
)
```

The version with the options object feels more cumbersome:

```r
list(
  tar_target(
    name = data,
    command = get_data(),
    options = tar_options(format = "qs")
  ),
  tar_rep(
    name = simulations,
    command = run_simulations(data),
    options = tar_options(
      memory = "transient",
      garbage_collection = TRUE,
      retrieval = "worker"
    )
  ),
  tar_target(
    name = app,
    command = create_wasm_bundle(simulations),
    options = tar_options(
      deployment  = "local",
      format = "file"
    )
  )
)
```

**Comment by hadley** [comment]
If you kept `format` at the top-level it looks a bit better:

```R
list(
  tar_target(
    name = data,
    command = get_data(),
    format = "qs"
  ),
  tar_rep(
    name = simulations,
    command = run_simulations(data),
    options = tar_options(
      memory = "transient",
      garbage_collection = TRUE,
      retrieval = "worker"
    )
  ),
  tar_target(
    name = app,
    command = create_wasm_bundle(simulations),
    format = "file"
    options = tar_options(deployment = "local")
  )
)
```

But maybe that doesn't move the needle. I don't have any sense of how frequently these options are used, because it would be certainly possible to have a compromise where only rarely used options were moved into a separate object. And maybe that's what you've already done with the `resources` argument.

**Comment by wlandau** [comment]
> I don't have any sense of how frequently these options are used, because it would be certainly possible to have a compromise where only rarely used options were moved into a separate object. 

It's tough to get a sense even from my end because use cases are so variable.

But in any case, I'll need to give https://design.tidyverse.org a full read. I appreciate the awareness that argument clutter can be an anti-pattern and that an options object is a good solution.
