### ISSUE TITLE
confusing names in tar_map with list of vectors

### ISSUE THREAD

**Issue by adamaltmejd** [ropensci/tarchetypes#37]
Starting to learn targets and migrating from drake so not sure if I'm doing things right but I cannot get the naming right when trying to run `tar_map()` over a list of vectors:

```
targets::tar_dir({ # tar_dir() runs code from a temporary directory.
targets::tar_script({
  list(
      tarchetypes::tar_map(
        values = list(a = list(c("foo", "bar"), c("test1", "test2"))),
        names = c("first", "second"),
        targets::tar_target(b, paste(a, collapse = "-"))
      )
  )
})
targets::tar_manifest()
})

# A tibble: 2 x 3
  name  command                                            pattern
  <chr> <chr>                                              <chr>  
1 b_1   "paste(c(\"foo\", \"bar\"), collapse = \"-\")"     NA     
2 b_2   "paste(c(\"test1\", \"test2\"), collapse = \"-\")" NA     
```

Seems targets are assigned numbers instead of values from the vector of names. If I remove the names it calls the two targets "foo" and "bar" but each target still has the intended content. Would have expected the second target to be named "test1".

```
targets::tar_dir({ # tar_dir() runs code from a temporary directory.
targets::tar_script({
  list(
      tarchetypes::tar_map(
        values = list(a = list(c("foo", "bar"), c("test1", "test2"))),
        targets::tar_target(b, paste(a, collapse = "-"))
      )
  )
})
targets::tar_manifest()
})
# A tibble: 2 x 3
  name  command                                            pattern
  <chr> <chr>                                              <chr>  
1 b_foo "paste(c(\"foo\", \"bar\"), collapse = \"-\")"     NA     
2 b_bar "paste(c(\"test1\", \"test2\"), collapse = \"-\")" NA     
```

Also, trying to add `pattern = map(a)` to the target produces `Error : x must not be empty`.

**Comment by wlandau** [comment]
`values`  should be a named data frame or list, where columns/elements are atomic vectors or symbol lists. The `names` argument uses `tidyselect` to choose among `names(values)` to create the target names. Here are examples similar to yours.

``` r
targets::tar_script({
  list(
    tarchetypes::tar_map(
      values = list(label1 = c("foo", "bar"), label2 = c("test1", "test2")),
      names = label1,
      targets::tar_target(b, label2)
    )
  )
})
  
targets::tar_manifest()
#> # A tibble: 2 x 3
#>   name  command     pattern
#>   <chr> <chr>       <chr>  
#> 1 b_foo "\"test1\"" <NA>   
#> 2 b_bar "\"test2\"" <NA>

targets::tar_script({
  list(
    tarchetypes::tar_map(
      values = list(label1 = c("foo", "bar"), label2 = c("test1", "test2")),
      names = starts_with("label"),
      targets::tar_target(b, label2)
    )
  )
})

targets::tar_manifest()
#> # A tibble: 2 x 3
#>   name        command     pattern
#>   <chr>       <chr>       <chr>  
#> 1 b_bar_test2 "\"test2\"" <NA>   
#> 2 b_foo_test1 "\"test1\"" <NA>
```

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by adamaltmejd** [comment]
Thanks for the quick reply and all your amazing work. The thing is that in my real project I want to specifically map vectors of variable length. In my code its a setting specifyin which variables the data set that I work with should be collapsed over (can be many). So I first run the code for `a = c("foo", "bar")` and then separately for `a = c("test")`. Your code is creating two separate targets, one for each element in `label2`.

I read in the help file that as you say values should be a list of vectors/data frame, but as you can see the nested list that I supplied did result in the correct mapping, only naming is wrong. `b_foo` returns `"foo-bar"` and `b_bar` returns `"test1-test"`. 

However the code below works!

```
targets::tar_dir({ # tar_dir() runs code from a temporary directory.
targets::tar_script({
  list(
      tarchetypes::tar_map(
        values = list(a = list(c("foo", "bar"), c("test1"), c(1, 2, 3)), names = c("foo", "test", "integers")),
        names = names,
        targets::tar_target(b, paste(a, collapse = "-"))
      )
  )
})
targets::tar_manifest()
})
  name       command                                        pattern
  <chr>      <chr>                                          <chr>  
1 b_integers "paste(c(1, 2, 3), collapse = \"-\")"          NA     
2 b_test     "paste(\"test1\", collapse = \"-\")"           NA     
3 b_foo      "paste(c(\"foo\", \"bar\"), collapse = \"-\")" NA     
```

Not sure why I can supply a vector of names as values and then assign it to names, but not assign a character vector immediately as the help page for `tar_map` says is possible:

```
Subset of names(values) used to generate the suffixes in the names of the new targets. You can supply symbols, a character vector, or tidyselect helpers like starts_with().
```

**Comment by adamaltmejd** [comment]
Ping @wlandau, not sure if you saw my reply?

**Comment by wlandau** [comment]
I did, but I didn't realize a response from me would be helpful. Substituting vectors of variable length are out of scope for static branching, but it sounds like you found something that works for you. The underlying mechanism is `substitute()`, and it looks the deparsed vectors are being substituted correctly. Seems like you can continue with your workaround.

**Comment by adamaltmejd** [comment]
Great, was thinking if perhaps my solution was perhaps the result of a bug but thats great. Thanks!

**Comment by c1au6i0** [comment]
> targets::tar_script({
>   list(
>     tarchetypes::tar_map(
>       values = list(label1 = c("foo", "bar"), label2 = c("test1", "test2")),
>       names = label1,
>       targets::tar_target(b, label2)
>     )
>   )
> })

In this example, could the element `label1` be defined in another single target?

**Comment by wlandau** [comment]
`tar_map()` uses static branching, so it does its thing before the pipeline runs. In other words, the `label1` target may not even exist yet when `tar_map()` is called. To define new targets based on the values of upstream targets, you can use [dynamic branching](https://books.ropensci.org/targets/dynamic.html).
