### ISSUE TITLE
tar_download()

### ISSUE THREAD

**Issue by wlandau** [ropensci/tarchetypes#38]
## Prework

* [x] I understand and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and  [contributing guidelines](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/tarchetypes/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

`tar_download()` could be a target factory that generates 2 targets: one `format = "url"` target to track a group of remote URLs with , and a downstream `format = "file"` target to download the URLs by running `download.file()` on each one.

Limitations:

1. URL targets are generally far enough upstream that we can expect users to pre-specify fixed URLs and destination files. Dynamically resolved URLs would not be an issue, but then destination files would be tricky to specify safely, correctly, and dynamically.
2. Because of the prespecification above, we would not allow dynamic branching (no `pattern` argument).

**Comment by wlandau** [comment]
cc @noamross, @jaredlander, @petrbouchal

**Comment by CorradoLanera** [comment]
My case is similar to the one below; as you mentioned, the returned error is OK and expected. My question is if you have suggestions on implementing custom code to overcome the limitation with minimal risk of errors.

Following is a running (with the expected error) reduced example from my case.

```r
# _targets.R
targets::tar_dir({
  targets::tar_script({
    compose_urls <- function(db) {
      seq_len(nrow(db)) |>
        purrr::map(compose_url, db = db)
    }
    
    compose_url <- function(id, db) {
      fnm <- string::str_glue("{id}-{db[['filename']][[id]]}")
      url <- db[["url"]][[id]]
      
      # pretend some checks and operations
      # on `url` and `fnm` here
      
      c(setNames(fnm, url))
    }
    
    list(
      # targets that finally lead to the myDb one
      tar_target(
        myDb,
        command = data.frame( # this would be generated from previous targets
          url = c("https://httpbin.org/etag/test", "https://r-project.org"),
          filename = c("downloaded_file_1", "downloaded_file_2")
        )
      ),
      
      tar_target(
        urls,
        command = compose_urls(myDb)
      ),
      
      tarchetypes::tar_download(
        downloadedFiles,
        urls = names(urls),
        paths = here::here("data", urls)
      )
      
      # other targets working with `downloadedFiles`
    ) 
  })
  targets::tar_make()
  targets::tar_read(urls)
})
```

**Comment by wlandau** [comment]
You might not use `tar_download()` if not all the URLs are fixed in advance, but you could create individual `tar_target(format = "url")` targets for each of the URLs, followed by a downstream `tar_target(command = down.load.file(...), format = "file")` for each URL.
