### ISSUE TITLE
Target factory to rerun after a given delay

### ISSUE THREAD

**Issue by wlandau** [ropensci/tarchetypes#39]
## Prework

* [x] I understand and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and  [contributing guidelines](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/tarchetypes/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Check the age of the target using `tar_timestamp()` and rerun the target if it is old enough (according to a user-supplied `difftime` object). This pretty much just requires a custom `tar_cue()` with `mode` equal to `"always"` or `"thorough"`, depending on when the target last ran. 

I don't think we can support dynamic branching in this one. Cues operate on all branches at once, but `tar_timestamp()` is branch-specific.

cc @noamross, @jaredlander, @petrbouchal

**Comment by wlandau** [comment]
I am open to name suggestions. My thoughts so far:

* `tar_interval()`
* `tar_periodically()`
* `tar_age()`
* `tar_schedule()`
* `tar_delay()`
* `tar_timer()`
* `tar_frequently()`

**Comment by noamross** [comment]
I like `tar_interval()`.  Another possibility is `tar_expire()`

**Comment by petrbouchal** [comment]
`tar_periodically()` and `tar_expire()` seem intuitively closest to what is in the tin. I think it might be nice to stick to the `tar_[noun]` pattern for target-generating functions, but nothing appropriate comes to mind.

`tar_after()`, `tar_timeout()`, `tar_every()`, `tar_timed()` come to mind.

**Comment by wlandau** [comment]
Thanks for the suggestions, they definitely help. After thinking it over, I like `tar_difftime()`. Since I plan to have users pass a `difftime` object to mark the interval, I find this to be clear and specific.

**Comment by wlandau** [comment]
And actually, there are at least two conceivable versions of `tar_difftime()`: one to force a target to rerun when it gets old enough, another to suppress a target *until* it gets old enough. I think we just want the former.

**Comment by wlandau** [comment]
On second thought, I don't think we even need a whole new target factory for this. We can probably just use `tar_force()` with a new `tar_older()` helper function that compares `Sys.time() - tar_timestamp()` to a user-supplied `difftime`.

**Comment by wlandau** [comment]
Let's first build some custom cues:

* `tar_cue_force(condition)`: equivalent to `tar_cue(mode = ifelse(any(condition), "always", "thorough"))`
* `tar_cue_skip(condition)`: equivalent to `tar_cue(mode = ifelse(any(condition), "never", "thorough"))`
* `tar_cue_age(name, age)`: equivalent to `tar_cue(mode = ifelse(any(Sys.time() - tar_timestamp_raw(name) > age), "always", "thorough"))`

Then build `tar_age()` for this issue on top of `tar_cue_age()`.

**Comment by petrbouchal** [comment]
Yes, my intuition initially was that I needed a special-purpose cue, so this makes good sense. For simplicity, `age` could be input as just an integer denoting the number of seconds - though not sure what implications that would have for the internals doing the time comparison.

**Comment by wlandau** [comment]
`tar_age()` and those cues I mentioned are now implemented.

> For simplicity, age could be input as just an integer denoting the number of seconds - though not sure what implications that would have for the internals doing the time comparison.

I prefer `difftime` because we don't know what scale of time the user is looking for. If it's seconds and most people turn out to want days, most users will end up supplying a high number for seconds and doing repetitive mental arithmetic.

**Comment by wlandau** [comment]
Related: turns out `tar_age()` etc. can work with dynamic branching if we take the max timestamp (so all the branches rerun if the youngest branch's data becomes old enough).
