### ISSUE TITLE
`tar_force()` recomputes artifact target even though `force` condition evaluates to `FALSE`

### ISSUE THREAD

**Issue by pat-s** [ropensci/tarchetypes#41]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] Confirm that your issue is most likely a genuine bug in `tarchetypes` and not a known limitation, a usage error, or a bug in another package that tarchetypes depends on.
* [x] If there is [already a relevant issue](https://github.com/ropensci/tarchetypes/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

I have a database target which I want to invalidate after a specific time (e.g. daily).

I've set a condition within `tar_force()` which should only evaluate to TRUE once a day.

While this works, I also see a new target in the console log that should not be there (`index_change`).
This targets runs on every run of `tar_make()` looks like an unwanted artifact.

## Reproducible example

``` r
library(targets)
library(tarchetypes)
tar_script({
  library(targets)
  suppressMessages(library(lubridate))
  list(
    tarchetypes::tar_force(index, seq_len(4),
      force = if (file.exists("_targets/objects/index")) as_date(file.info("_targets/objects/index")$mtime) < (lubridate::today())
    )
  )
})
tar_make()
#> ● run target index_change
#> ● run target index
#> ● end pipeline
tar_make()
#> ● run target index_change
#> ✓ skip target index
#> ● end pipeline
```

<sup>Created on 2021-04-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                                      
#>  version  R version 4.0.5 Patched (2021-03-31 r80136)
#>  os       macOS Big Sur 10.16                        
#>  system   x86_64, darwin17.0                         
#>  ui       X11                                        
#>  language (EN)                                       
#>  collate  en_US.UTF-8                                
#>  ctype    en_US.UTF-8                                
#>  tz       Europe/Zurich                              
#>  date     2021-04-21                                 
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  backports     1.2.1   2020-12-09 [1] CRAN (R 4.0.4)
#>  callr         3.6.0   2021-03-28 [1] CRAN (R 4.0.5)
#>  cli           2.4.0   2021-04-05 [1] CRAN (R 4.0.5)
#>  codetools     0.2-18  2020-11-04 [2] CRAN (R 4.0.5)
#>  crayon        1.4.1   2021-02-08 [1] CRAN (R 4.0.4)
#>  data.table    1.14.0  2021-02-21 [1] CRAN (R 4.0.4)
#>  digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.4)
#>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.4)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.4)
#>  fansi         0.4.2   2021-01-15 [1] CRAN (R 4.0.4)
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.4)
#>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.4)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.0.5)
#>  htmltools     0.5.1.1 2021-01-22 [1] CRAN (R 4.0.4)
#>  igraph        1.2.6   2020-10-06 [1] CRAN (R 4.0.4)
#>  knitr         1.32    2021-04-14 [1] CRAN (R 4.0.5)
#>  lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.0.4)
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.4)
#>  pillar        1.6.0   2021-04-13 [1] CRAN (R 4.0.5)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.4)
#>  processx      3.5.1   2021-04-04 [1] CRAN (R 4.0.5)
#>  ps            1.6.0   2021-02-28 [1] CRAN (R 4.0.5)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.4)
#>  R.cache       0.14.0  2019-12-06 [1] RSPM (R 4.0.4)
#>  R.methodsS3   1.8.1   2020-08-26 [1] CRAN (R 4.0.4)
#>  R.oo          1.24.0  2020-08-26 [1] RSPM (R 4.0.4)
#>  R.utils       2.10.1  2020-08-26 [1] RSPM (R 4.0.4)
#>  R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.4)
#>  reprex        2.0.0   2021-04-02 [1] CRAN (R 4.0.5)
#>  rlang         0.4.10  2020-12-30 [1] CRAN (R 4.0.4)
#>  rmarkdown     2.7     2021-02-19 [1] CRAN (R 4.0.5)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.4)
#>  stringi       1.5.3   2020-09-09 [1] CRAN (R 4.0.4)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.4)
#>  styler        1.4.1   2021-03-30 [1] CRAN (R 4.0.5)
#>  tarchetypes * 0.1.1   2021-03-28 [1] CRAN (R 4.0.5)
#>  targets     * 0.3.1   2021-03-28 [1] CRAN (R 4.0.5)
#>  tibble        3.1.1   2021-04-18 [1] CRAN (R 4.0.5)
#>  tidyselect    1.1.0   2020-05-11 [1] CRAN (R 4.0.4)
#>  utf8          1.2.1   2021-03-12 [1] CRAN (R 4.0.5)
#>  vctrs         0.3.7   2021-03-29 [1] CRAN (R 4.0.5)
#>  withr         2.4.2   2021-04-18 [1] CRAN (R 4.0.5)
#>  xfun          0.22    2021-03-11 [1] CRAN (R 4.0.5)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.4)
#> 
#> [1] /Users/pjs/Library/R/4.0/library
#> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

## Expected result

No artifact target should appear.

**Comment by wlandau** [comment]
The `index_change` target is part of the mechanism of `tar_force()`. It allows `tar_force()` (and `tar_change()`) to use conditions that dynamically depend on upstream targets, rather than just the values of pre-existing global objects. `index_change` needs to always run in order to figure out whether  `index` needs to run at all. To create a similar pipeline without this extra target, use something like `tar_target(..., cue = tar_cue_force(...))`.
