### ISSUE TITLE
Convenience triggers for (time-based) target invalidation

### ISSUE THREAD

**Issue by pat-s** [ropensci/tarchetypes#42]
## Prework

* [x] I understand and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and  [contributing guidelines](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x If there is [already a relevant issue](https://github.com/ropensci/tarchetypes/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

#41 shows how a time based invalidation could happen:

```r
tarchetypes::tar_force(index, seq_len(4),
  force = if (file.exists("_targets/objects/index")) as_date(file.info("_targets/objects/index")$mtime) < (lubridate::today())
    )
```

I wonder if it would make sense to add some time-based convenience options to `force` to simplify achieving this and improve readability.

```r
tarchetypes::tar_force(index, seq_len(4),
  force = "daily"
    )

tarchetypes::tar_force(index, seq_len(4),
  force = "weekly"
    )
```

Not sure what is happening behind the scenes and if this is possible in the first place but it would help a lot :)

**Comment by wlandau** [comment]
I actually recently added `tar_age()` and `tar_cue_age()` to cover this.

**Comment by pat-s** [comment]
Ah awesome! Works great 🎉
