### ISSUE TITLE
tar_knitr_deps() analyses call to knitr::read_chunk that is commented out

### ISSUE THREAD

**Issue by rgayler** [ropensci/tarchetypes#51]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] Confirm that your issue is most likely a genuine bug in `tarchetypes` and not a known limitation, a usage error, or a bug in another package that tarchetypes depends on.
* [x] If there is [already a relevant issue](https://github.com/ropensci/tarchetypes/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

I am using tarchetypes::tar_knitr_deps() to analyse the dependencies in an Rmarkdown file and discovered that it analyses a call to knitr::read_chunk() that is commented out.

## Reproducible example

* Open an Rstudio session
* Create and save file `test_report.Rmd` with contents:
````
---
title: "test report"
output: html_document
---

```{r}
# knitr::read_chunk("non_existent_file.R")
```
````
* Execute `tarchetaypes::tar_knitr_deps("test_report.Rmd")` in the console. (This assumes the working directory is set appropriately.)
* This generates the following error message, which indicates that `tar_knitr_deps()` tried to analyse the commented out call to `knitr::read_chunk()`.

```
Quitting from lines 7-8 (test_report.Rmd) 
Error: Could not parse knitr report test_report.Rmd to detect dependencies: cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'non_existent_file.R': No such file or directory
```

## Expected result

I expected `tar_knitr_deps("non_existent_file.R")` to return `character(0)` because there is no executable code to contain dependencies.

It may be that  `tar_knitr_deps()` won't work with `knitr::read_chunk()`, but I expected all code comments to be effectively invisible to `tar_knitr_deps().

## Diagnostic information

```
> traceback()
14: stop(tar_condition_validate(...))
13: throw_validate("Could not parse knitr report ", path, " to detect dependencies: ", 
        conditionMessage(e))
12: value[[3L]](cond)
11: tryCatchOne(expr, names, parentenv, handlers[[1L]])
10: tryCatchList(expr, classes, parentenv, handlers)
9: tryCatch(parse(text = knitr_lines(path)), error = function(e) {
       throw_validate("Could not parse knitr report ", path, " to detect dependencies: ", 
           conditionMessage(e))
   })
8: knitr_expr(path)
7: FUN(X[[i]], ...)
6: lapply(X = x, FUN = as_function(f), ...)
5: map(path, knitr_deps)
4: unlist(map(path, knitr_deps))
3: unique(unlist(map(path, knitr_deps)))
2: sort(unique(unlist(map(path, knitr_deps))))
1: tarchetypes::tar_knitr_deps("test_report.Rmd")
```
```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.10

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8     LC_MONETARY=en_AU.UTF-8   
 [6] LC_MESSAGES=en_AU.UTF-8    LC_PAPER=en_AU.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] usethis_2.0.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6             pillar_1.6.0           compiler_4.0.3         later_1.2.0            workflowr_1.6.2        prettyunits_1.1.1     
 [7] sys_3.4                remotes_2.3.0          tarchetypes_0.2.0.9000 targets_0.4.2          tools_4.0.3            pkgbuild_1.2.0        
[13] digest_0.6.27          jsonlite_1.7.2         evaluate_0.14          lifecycle_1.0.0        tibble_3.1.1           pkgconfig_2.0.3       
[19] rlang_0.4.11           igraph_1.2.6           rstudioapi_0.13        cli_2.5.0              curl_4.3.1             yaml_2.2.1            
[25] xfun_0.22              stringr_1.4.0          withr_2.4.2            knitr_1.33             askpass_1.1            fs_1.5.0              
[31] vctrs_0.3.8            rprojroot_2.0.2        tidyselect_1.1.1       glue_1.4.2             data.table_1.14.0      R6_2.5.0              
[37] processx_3.5.2         fansi_0.4.2            rmarkdown_2.8          callr_3.7.0            purrr_0.3.4            magrittr_2.0.1        
[43] credentials_1.3.0      codetools_0.2-17       ps_1.6.0               promises_1.2.0.1       ellipsis_0.3.2         htmltools_0.5.1.1     
[49] httpuv_1.6.1           utf8_1.2.1             stringi_1.6.1          openssl_1.4.4          crayon_1.4.1          
```

```
> packageDescription("tarchetypes")$GithubSHA1
[1] "2ec501364a80618cd8b3e072148be8dd6ecaab4d"
```

**Comment by wlandau** [comment]
The error actually comes from `knitr::purl()`/`knitr::knit(tangle = TRUE)`, so there is nothing I can do from `tarchetypes`. I suspect `knitr` is trying to statically detect external R scripts and pull the code from those scripts as if it were inline in the report. Because users may wish to declare `tar_load()`/`tar_read()` target dependencies, these external scripts should be inspected too in the general case,  but perhaps `knitr` should ignore commented calls to `read_chunk()`.

```` r
lines <- c(
  "---",
  "title: \"test report\"",
  "output: html_document",
  "---",
  "",
  "```{r}",
  "# knitr::read_chunk(\"non_existent_file.R\")",
  "```"
)
tmp <- tempfile()
writeLines(lines, tmp)
knitr::purl(tmp)
#> processing file: /var/folders/k3/q1f45fsn4_13jbn0742d4zj40000gn/T//RtmpqYTYvx/file2e401317498d
#> Warning in file(con, "r"): cannot open file 'non_existent_file.R': No such file
#> or directory
#> Quitting from lines 7-8 (/var/folders/k3/q1f45fsn4_13jbn0742d4zj40000gn/T//RtmpqYTYvx/file2e401317498d)
#> Error in file(con, "r"): cannot open the connection
````

<sup>Created on 2021-05-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by rgayler** [comment]
Thanks @wlandau . I looked in the code of tar_knitr_deps(), but got lost before I could determine whether the problem actually arose in knitr:: . I'll take it over to knitr:: to see whether that behaviour was intended.
