### ISSUE TITLE
tar_render renders distill but returns an error (invalidating the DAG)

### ISSUE THREAD

**Issue by CorradoLanera** [ropensci/tarchetypes#79]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] Confirm that your issue is a genuine bug in `tarchetypes` and not a known limitation, usage error, or issue from another package that `tarchetypes` depends on. If you are unsure, please submit a discussion thread instead.
* [x] If there is [already a relevant issue](https://github.com/ropensci/tarchetypes/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

When try to render a {distill} article using `tar_render`, it will be correctly rendered, but it returns a strange error: 
```r
> targets::tar_make()
* start target report
x error target report
* end pipeline
Error : Distill articles cannot be previewed in this version of RStudio.
Please update to version 1.2.718 or higher at https://www.rstudio.com/products/rstudio/download/
```

Searching the web, I have discovered [this](https://stackoverflow.com/questions/68888905/cannot-render-distill-article-in-a-targets-pipeline) discussion reporting the same issue (even if I _can_ create the HTML report, which _is_ rendered!)

The issue seems related (as stated in an answer to that SO thread) to a missing environmental variable. As suggested, I have also tried `rmarkdown::render("distill_target_test.Rmd")`, which correctly renders without any error (nor preview...)

My verions are:
OS: Windows 11 Pro for Workstations 21H2
R: 4.1.2
RStudio: 2021.09.0 Build 351 
{targets}: 0.8.1.9000
{tarchetypes}: 0.3.2.9000
{distill}: 1.3

## Reproducible example

* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

Involving an environment, I have set-up a minimal renv-project at [CorradoLanera/targets_distill](https://github.com/CorradoLanera/targets_distill). Just clone and run `run.R`.

So the main problem is that the error invalidates the network, resulting in an errored node. As I said, the report _is_ rendered!

## Expected result

Do not receive an error, or at least the option of safely ignoring it with no invalidation of the DAG's node for the report.

### Reproducible example
https://github.com/CorradoLanera/targets_distill

### Session Info

<details>
  <summary>Session info</summary>

```r
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
system code page: 65001

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
 [1] jquerylib_0.1.4    pillar_1.6.4       compiler_4.1.2    
 [4] remotes_2.4.1      targets_0.8.1.9000 tools_4.1.2       
 [7] digest_0.6.28      downlit_0.4.0      jsonlite_1.7.2    
[10] lubridate_1.8.0    evaluate_0.14      memoise_2.0.0     
[13] lifecycle_1.0.1    tibble_3.1.6       pkgconfig_2.0.3   
[16] rlang_0.4.12       igraph_1.2.8       cli_3.1.0         
[19] rstudioapi_0.13    distill_1.3        yaml_2.2.1        
[22] xfun_0.28          fastmap_1.1.0      stringr_1.4.0     
[25] withr_2.4.2        knitr_1.36         generics_0.1.1    
[28] vctrs_0.3.8        rprojroot_2.0.2    tidyselect_1.1.1  
[31] glue_1.5.0         data.table_1.14.2  R6_2.5.1          
[34] processx_3.5.2     fansi_0.5.0        bookdown_0.24     
[37] rmarkdown_2.11     callr_3.7.0        purrr_0.3.4       
[40] magrittr_2.0.1     codetools_0.2-18   ps_1.6.0          
[43] ellipsis_0.3.2     htmltools_0.5.2    renv_0.14.0       
[46] utf8_1.2.2         stringi_1.7.5      cachem_1.0.6      
[49] crayon_1.4.2  
```

</details>

### Traceback

```r
> rlang::last_error()
<error/tar_condition_run>
callr subprocess failed: Distill articles cannot be previewed in this version of RStudio.
Please update to version 1.2.718 or higher at https://www.rstudio.com/products/rstudio/download/

Visit https://books.ropensci.org/targets/debugging.html for debugging advice.
Backtrace:
 1. targets::tar_make()
 2. targets:::callr_outer(...)
 3. base::tryCatch(...)
 4. base:::tryCatchList(expr, classes, parentenv, handlers)
 5. base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6. value[[3L]](cond)
 7. targets::tar_throw_run(...)
Run `rlang::last_trace()` to see the full context.
> rlang::trace_back()
x
```

### SHA-1 of the GitHub commit of `tarchetypes` currently installed

4113a6143ed4b14b1f425090db672f0f54da1117

**Comment by CorradoLanera** [comment]
Additional notes:

- put `Sys.setenv("RSTUDIO_VERSION" = '2021.09.0')` in the setup chunk of the Rmd (as suggested in the [mentioned SO question](https://stackoverflow.com/questions/68888905/cannot-render-distill-article-in-a-targets-pipeline)) works.
- put `withr::local_envvar(list(RSTUDIO_VERSION = '2021.09.0'))` in the setup chunk of the Rmd does not work.
- set `RSTUDIO_VERSION="2021.09.0"` in a project's `.Renviron` works.
- source as local job
    ```r
    # run.R
    withr::with_envvar(
      list(RSTUDIO_VERSION = "2021.09.0"),
      targets::tar_make()
    )
    ```
  (instead of the simple `targets::tar_make()` alone) works.
- source as local job
    ```r
    # run.R
    withr::local_envvar(list(RSTUDIO_VERSION = "2021.09.0"))
    targets::tar_make()
    ```
  does not work.

**Comment by wlandau** [comment]
`tar_make()` runs the pipeline in a new R session (a `callr::r()` process) and that new session usually only has the environment variables from the project's .Renviron. That is probably why the error happens only inside your pipeline and not `rmarkdown::render()` outside the pipeline. I recommend the project-level `.Renviron` workaround you proposed. This is not a bug in `tarchetypes`.
