### ISSUE TITLE
quarto targets

### ISSUE THREAD

**Issue by wlandau** [ropensci/tarchetypes#89]
## Prework

* [x] I understand and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and  [contributing guidelines](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/tarchetypes/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

From @petrbouchal, https://github.com/ropensci/targets/discussions/813

**Comment by mccarthy-m-g** [comment]
This would be great!

FYI, there’s a quarto [R package](https://github.com/quarto-dev/quarto-r) with a `quarto_render()` function, so this is hopefully pretty trivial to add.

**Comment by wlandau** [comment]
Just starting to look at Quarto. https://www.njtierney.com/post/2022/04/11/rmd-to-qmd/ convinces me that brand new target factories for `quarto_render()` are a good idea:

> From what I can tell, quarto appears to be a lot more consistent. For example, instead of having a special [_bookdown.yml file](https://github.com/njtierney/rmd4sci/blob/master/_bookdown.yml) for your bookdown, which also needs a special [_output.yml](https://github.com/njtierney/rmd4sci/blob/master/_output.yml) file, there is just now one single [_quarto.yml](https://github.com/njtierney/qmd4sci/blob/master/_quarto.yml) file. It also means that there will likely be less pain if you need to change from a book to a website, to slides, to something else.

Also, it looks like Pandoc shenanigans may not be as bad.

The unified `_quarto.yaml` looks really nice. To get the source files to scrape for R code chunk dependencies, it seems like we can just look at the `chapters:` field (or are there other qmd files listed in other fields). And then other YAML fields have non-R dependency input files. And in the case when `_quarto.yaml` does not exist, we look at the `input` argument itself. 

Output files might take some more figuring out since `quarto_render()` does not return the output paths. For single output files, `quarto_inspect()` looks promising because it does have an output path. I am hoping it will show similar output file info for entire quarto projects.

I am probably not going to modify `freeze:`, but it seems like a good point to mention in the docs.

**Comment by wlandau** [comment]
Quarto projects are flexible and variable enough that I think I will need users to declare all the files manually in the upcoming `tar_quarto()`. Arguments will be:

1. The target name.
1. `input`: value passed to the `input` argument of `quarto::quarto_render()`.
1. `files`: files and directories with input and output that `targets` should track for changes. These files include rendered HTML reports, `_quarto.yml`, bibliographies, stylesheets, and/or `_book`. Not all the files need to exist before rendering, but they should exist afterwards. Files in the `sources` argument are automatically tracked for changes, so there is no need to include them in `files`.
1. `sources`: literate programming source documents (`*.qmd` and `*.Rmd` files) that use output from upstream targets. These source documents reference dependent targets with `tar_load()` and `tar_read()` in active R code chunks. The default value is a character vector of all the `*.qmd` and `*.Rmd` files that can be found in the `input` argument.
1. Explicit formal arguments passed to `quarto::quarto_render()`. `as_job` will always be `FALSE` and I will not expose it. And I will probably set defaults of `quiet` to `TRUE` and `execute_daemon` to `FALSE`.
1. Explicit formal arguments to `tar_target_raw()`.

`tar_quarto_rep()` will be like `tar_render_rep()`: act on a single input file and generate multiple output files by dynamically branching over parameters.
